@CustomerService_Dapr_HostAddress = http://localhost:3602
@SubscriptionService_Dapr_HostAddress = http://localhost:3601

### update job retries

POST {{CustomerService_Dapr_HostAddress}}/v1.0/bindings/zeebe-command
dapr-app-id: customer-service
Accept: application/json
Content-Type: application/json

{
  "data": {
    "jobKey": 2251799814281450,
    "retries": 10
  },
  "operation": "update-job-retries"
}

### publish message

# @subscriptionId = 373369f0d5064006a553cf113ed2aae6

POST {{SubscriptionService_Dapr_HostAddress}}/v1.0/bindings/zeebe-command
dapr-app-id: subscription-service
Accept: application/json
Content-Type: application/json

{
  "data": {
    "messageName": "on-information-received",
    "correlationKey": "373369f0d5064006a553cf113ed2aae6",
    "timeToLive": "1m"
  },  
  "operation": "publish-message"
}

