### register a new customer (start process)

POST http://localhost:3602/v1.0/bindings/zeebe-command
dapr-app-id: customer-service
Accept: application/json
Content-Type: application/json

{
 "data": {
    "bpmnProcessId": "register-customer-process_1434vxu",
    "version": 4,
    "variables": {
      "firstName": "March",
      "lastName": "Simpson",
      "birthDate": "1980-06-06",
      "email": "march.simpson@thesimpsons.movie"
    }
  }, 
  "operation": "create-instance"
}