### register a new subscription (start process)

# @name registerSubscription

POST http://localhost:3601/v1.0/bindings/zeebe-command
dapr-app-id: subscription-service
Accept: application/json
Content-Type: application/json

{
 "data": {
    "bpmnProcessId": "Subscription_Process_Workflow",
    "variables": {
      "firstName": "Lisa",
      "lastName": "Simpson",
      "birthDate": "1980-12-31",
      "email": "lisa.simpson@thesimpsons.movie",
      "productId": "home", 
      "loanAmount": 200000,
      "insuredAmount": 100000
    }
  }, 
  "operation": "create-instance"
}

### get all registered subscription requests

GET http://localhost:5010/api/subscriptions?take=5
accept: application/json
content-type: application/json

