version: "3.7"

services:

  subscription-service:
    container_name: subscription-service
    image: subscription-service:${TAG:-latest}
    build:
      context: .
      dockerfile: ./services/SubscriptionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5001:8080"       # app
      - "3601:3500"
      - "60001:50001"
      - "9001:9090"

  subscription-service-dapr:
    container_name: subscription-service-dapr
    image: daprio/daprd:1.12.0
    network_mode: "service:subscription-service"
    command: [ "./daprd",
               "-app-id", "subscription-service",
               "-dapr-http-port", "3500",
               "-dapr-grpc-port", "50001",
               "-metrics-port", "9090",
               "-app-port", "8080",   # app
               "-components-path", "/components",
               "-config", "/configuration/dapr-config.yaml"
    ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
    depends_on:
      - subscription-service
      
  customer-service:
    container_name: customer-service
    image: customer-service:${TAG:-latest}
    build:
      context: .
      dockerfile: ./services/CustomerService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5002:8080"       # app
      - "3602:3500"
      - "60002:50001"
      - "9002:9090"

  customer-service-dapr:
    container_name: customer-service-dapr
    image: daprio/daprd:1.12.0
    network_mode: "service:customer-service"
    command: [ "./daprd",
               "-app-id", "customer-service",
               "-dapr-http-port", "3500",
               "-dapr-grpc-port", "50001",
               "-metrics-port", "9090",
               "-app-port", "8080",   # app
               "-components-path", "/components",
               "-config", "/configuration/dapr-config.yaml"
    ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
    depends_on:
      - customer-service
        
  customer-experience-api:
    container_name: customer-experience-api
    image: customer-experience-service:${TAG:-latest}
    build:
      context: .
      dockerfile: ./services/CustomerExperienceAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5010:8080"       # app
      - "3610:3500"
      - "60010:50001"
      - "9010:9090"

  customer-experice-api-dapr:
    container_name: customer-experience-api-dapr
    image: daprio/daprd:1.12.0
    network_mode: "service:customer-experience-api"
    command: [ "./daprd",
               "-app-id", "customer-experience-api",
               "-dapr-http-port", "3500",
               "-dapr-grpc-port", "50001",
               "-metrics-port", "9090",
               "-app-port", "8080",   # app
               "-components-path", "/components",
               "-config", "/configuration/dapr-config.yaml"
    ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
    depends_on:
      - customer-experience-api
        
#  customer-web:
#    container_name: customer-web
#    image: customer-web:${TAG:-latest}
#    build:
#      context: .
#      dockerfile: ./clients/CustomerWeb/Dockerfile
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#    ports:
#      - "5100:8080"       # app

  