version: "3.7"

services:

  maildev:
    container_name: maildev
    image: maildev/maildev
    restart: unless-stopped
    ports:
      - "4000:1080"
      - "4025:1025"
    networks:
      - subscription-processing-demo

  zipkin:
    container_name: zipkin2
    image: openzipkin/zipkin
    restart: unless-stopped
    ports:
      - "9412:9411"
    networks:
      - subscription-processing-demo
      
  mongo:
    container_name: mongo
    image: mongo:5.0.15
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    networks:
      - subscription-processing-demo
    volumes:
      - mongo-data:/var/lib/mongo"

  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    networks:
      - subscription-processing-demo
    volumes:
      - mssql-data:/var/opt/mssql
    
volumes:
  mongo-data:
  mssql-data:

networks:
  subscription-processing-demo: