### get subscription requests

GET http://localhost:3610/api/subscriptions?take=15
dapr-app-id: ods-service
context-type: application/json

### post a new subscription request

POST http://localhost:3601/api/subscriptions
dapr-app-id: subscription-service
content-type: application/json

{
  "firstName": "Homer",
  "lastName": "Simpson",
  "email": "homer.simpson@thesimpsons.movie",
  "birthDate": "1976-01-06",
  "productId": "1", 
  "loanAmount": 200000,
  "insuredAmount": 100000
}

### register a new customer

POST http://localhost:3602/register-customer
dapr-app-id: customer-service
Content-Type: application/json

{
  "firstName": "Homer",
  "lastName": "Simpson",
  "email": "homer.simpson@thesimpsons.movie",
  "birthDate": "1976-01-06"
}   

### get customer




