namespace Core.Helpers;

public static class Calculator
{
    // "almost" generated by AI
    public static int CalculateAge(DateOnly birthdate)
    {
        var today = DateTime.Today;
        var age = today.Year - birthdate.Year;
        if (birthdate > DateOnly.FromDateTime(today).AddYears(-age))
        {
            age--;
        }

        return age;
    }
}