# nonk8s
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: on-information-received
spec:
  type: bindings.zeebe.jobworker
  version: v1
  metadata:
    - name: gatewayAddr
      value: "host.docker.internal:26500"
    - name: gatewayKeepAlive
      value: "45s"
    - name: usePlainTextConnection
      value: "true"
    - name: workerName
      value: "on-information-received-worker"
    - name: workerTimeout
      value: "30s"
    - name: requestTimeout
      value: "15s"
    - name: jobType
      value: "on-information-received"
    - name: maxJobsActive
      value: "32"
    - name: concurrency
      value: "4"
    - name: pollInterval
      value: "100ms"
    - name: pollThreshold
      value: "0.3"
scopes:
  - subscription-service
