apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secrets
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: ./components/secretstore.json
    - name: nestedSeparator
      value: "."
scopes:
  - subscription-service
  - customer-service
  - ods-service
