apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore-mongo
spec:
  type: state.mongodb
  version: v1
  metadata:
    - name: host
      value: localhost:27017 # Required unless "server" field is set . Example: "mongo-mongodb.default.svc.cluster.local:27017"
    - name: operationTimeout
      value: "5s" # Optional. default: "5s"
    - name: actorStateStore
      value: "false"
    - name: params
      value: "?authSource=admin"

