apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientService
  namespace: {{ .Values.namespace }}
  labels:
    app: onecop
    service: clientService
spec:
  replicas: 1
  selector:
    matchLabels:
      service: clientService
  template:
    metadata:
      labels:
        app: onecop
        service: clientService
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "clientService"
        dapr.io/app-port: "8080"
        dapr.io/config: "dapr-config"
        dapr.io/log-as-json: "true"
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        name: client
        image: http://localhost:5000/clientService:1.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /hc
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          
---

apiVersion: v1
kind: Service
metadata:
  name: clientService
  namespace: {{ .Values.namespace }}
  labels:
    app: onecop
    service: clientService
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 5002
      protocol: TCP
    - name: dapr-http
      port: 3500
      targetPort: 3500
      protocol: TCP
    - name: dapr-grpc
      port: 50001
      targetPort: 50001
      protocol: TCP
  selector:
    service: clientService
    

