apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: {{ .Values.hostName }}
      http:
        paths:
          - path: /subscription
            pathType: Prefix
            backend:
              service:
                name: subscriptionService
                port:
                  number: 5001
          - path: /client
            pathType: Prefix
            backend:
              service:
                name: clientService
                port:
                  number: 5002