apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  namespace: {{ .Values.namespace }}
  labels:
    app: onecop
    service: customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: customer-service
  template:
    metadata:
      labels:
        app: onecop
        service: customer-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "customer-service"
        dapr.io/app-port: "8080"
        dapr.io/config: "dapr-config"
        dapr.io/log-as-json: "true"
        dapr.io/log-level: "info"
        dapr.io/sidecar-memory-request: "250Mi"
        dapr.io/sidecar-cpu-request: "100m"
        dapr.io/sidecar-memory-limit: "4000Mi"
        dapr.io/sidecar-cpu-limit: "1"
        dapr.io/sidecar-liveness-probe-period-seconds: "20"
        dapr.io/sidecar-readiness-probe-period-seconds: "20"  
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        name: customer-service
        image: {{ .Values.registryUrl }}/customer-service:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          
---

apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: {{ .Values.namespace }}
  labels:
    app: onecop
    service: customer-service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 5002
      protocol: TCP
    - name: dapr-http
      port: 3500
      targetPort: 3500
      protocol: TCP
    - name: dapr-grpc
      port: 50001
      targetPort: 50001
      protocol: TCP
  selector:
    service: customer-service
    

