apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: onecop
    version: v1
  name: rabbitmq
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5672

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "data"
      port: 5672
      targetPort: 5672
  selector:
    app: rabbitmq
