kind: Deployment
apiVersion: apps/v1
metadata:
  name: zipkin
  namespace: {{ .Values.namespace }}
  labels:
    app: onecop
    service: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      service: zipkin
  template:
    metadata:
      labels:
        app: onecop
        service: zipkin
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9411
              protocol: TCP

---

kind: Service
apiVersion: v1
metadata:
  name: zipkin
  namespace: {{ .Values.namespace }}
  labels:
    app: onecop
    service: zipkin
spec:
  ports:
    - port: 9413
      targetPort: 9411
      protocol: TCP
      name: zipkin
  selector:
    service: zipkin
