version: "3.7"

services:

  client-api:
    container_name: client-api
    image: client-api:${TAG:-latest}
    build:
      context: .
      dockerfile: ./ClientAPI/Dockerfile
    environment:
      - NAMESPACE=demo
    ports:
      - "5001:8080"       # app
      - "6001:3500"
      - "60001:50001"
      - "9991:9090"

  client-api-dapr:
    container_name: client-api-dapr
    image: daprio/daprd:1.10.0
    network_mode: "service:client-api"
    command: [ "./daprd",
               "-app-id", "client-api",
               "-dapr-http-port", "3500",
               "-dapr-grpc-port", "50001",
               "-metrics-port", "9090",
               "-app-port", "8080",   # app
               "-placement-host-address", "dapr-placement:50007",
               "-components-path", "/components",
               "-config", "/configuration/dapr-config.yaml"
    ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
    depends_on:
      - client-api
        
  subscription-api:
    container_name: subscription-api
    image: subscription-api:${TAG:-latest}
    build:
      context: .
      dockerfile: ./SubscriptionAPI/Dockerfile
    environment:
      - NAMESPACE=demo
    ports:
      - "5002:8080"       # app
      - "6002:3500"
      - "60002:50001"
      - "9992:9090"

  subscription-api-dapr:
    container_name: subscription-api-dapr
    image: daprio/daprd:1.10.0
    network_mode: "service:subscription-api"
    command: [ "./daprd",
               "-app-id", "subscription-api",
               "-dapr-http-port", "3500",
               "-dapr-grpc-port", "50001",
               "-metrics-port", "9090",
               "-app-port", "8080",   # app
               "-placement-host-address", "dapr-placement:50007",
               "-components-path", "/components",
               "-config", "/configuration/dapr-config.yaml"
    ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
    depends_on:
      - subscription-api

  dapr-placement:
    image: daprio/dapr:1.11.0
    command: [ "./placement", "-port", "50007", "-log-level", "error" ]
    ports:
      - "50007:50007"

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin-slim
    ports:
      - "9412:9411"  # avoid conflicts with default zipkin installation
    