apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: demo
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: redis:6379
    - name: redisPassword
      value: 
    - name: actorStateStore
      value: "false"
scopes:
  - subscription-service
  - client-service