apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: api/subscriptions/normalize
  namespace: demo
spec:
  type: bindings.zeebe.jobworker
  version: v1
  metadata:
    - name: gatewayAddr
      value: host.docker.internal:26500
    - name: gatewayKeepAlive
      value: 45s
    - name: usePlainTextConnection
      value: true
    - name: jobType
      value: normalize
    - name: workerName
      value: subscription-worker
    - name: maxJobsActive
      value: 32
    - name: concurrency
      value: 4
    - name: pollInterval
      value: 100ms
    - name: pollThreshold
      value: 0.3
scopes:
  - subscription-api